# Smart Climate Services

generate_dashboard:
  name: Generate Dashboard
  description: Generate a customized dashboard YAML for your Smart Climate device. The dashboard will be sent via persistent notification for you to copy and use.
  fields:
    climate_entity_id:
      name: Climate Entity
      description: The Smart Climate entity to generate a dashboard for
      required: true
      example: climate.living_room_ac
      selector:
        entity:
          filter:
            - integration: smart_climate
              domain: climate